---
# tasks file for db
- name: Change mongod config
  template:
    src: mongod.conf.j2
    dest: /etc/mongodb.conf
    mode: 0644
  notify: restart mongodb

- name: Show info about the env this host belongs to
  debug: msg="This host is in {{ env }} environment!!!"
